In [1]:
import tensorflow as tf

In [2]:
save_file='./model.ckpt'

In [3]:
# Two tensor variables:weights and bias
weights=tf.Variable(tf.truncated_normal([2,3]))
bias=tf.Variable(tf.truncated_normal([3]))

In [4]:
# Class used to save or restor Tensor Variables
saver=tf.train.Saver()

In [5]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))
    # Save the model
    saver.save(sess,save_file)

Weights:
[[-0.56376541  1.77240705  1.48376095]
 [ 0.42539659 -0.76024014 -0.63782871]]
Bias:
[ 0.94403434 -0.76168764  0.73779231]


In [6]:
# Remove the previous weights and bias
tf.reset_default_graph()

In [7]:
# Create 2 variables:weights,biases
weights=tf.Variable(tf.truncated_normal([2,3]))
bias=tf.Variable(tf.truncated_normal([3]))

saver=tf.train.Saver()

with tf.Session() as sess:
    saver.restore(sess,save_file)
    
    # Show the values of weights and biases
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))


INFO:tensorflow:Restoring parameters from ./model.ckpt
Weights:
[[-0.56376541  1.77240705  1.48376095]
 [ 0.42539659 -0.76024014 -0.63782871]]
Bias:
[ 0.94403434 -0.76168764  0.73779231]


In [8]:
# Let's see how to train a model and save its weights
# Remove previous Tensors and operations

tf.reset_default_graph()
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np


In [9]:
learning_rate=0.001
n_input=784
n_classes=10
mnist=input_data.read_data_sets('.',one_hot=True)

Extracting ./train-images-idx3-ubyte.gz
Extracting ./train-labels-idx1-ubyte.gz
Extracting ./t10k-images-idx3-ubyte.gz
Extracting ./t10k-labels-idx1-ubyte.gz


In [10]:
# Features and labels
features=tf.placeholder(tf.float32,[None,n_input])
labels=tf.placeholder(tf.float32,[None,n_classes])

# Weights & bias

weights=tf.Variable(tf.random_normal([n_input,n_classes]))
bias=tf.Variable(tf.random_normal([n_classes]))

# logits -xW+b
logits=tf.add(tf.matmul(features,weights),bias)

# Define loss and optimizer

cost=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits,labels=labels))
optimizer=tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction=tf.equal(tf.argmax(logits,1),tf.argmax(labels,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction,tf.float32))




In [11]:
# Train the model
import math
save_file='./train_model.ckpt'
batch_size=128
n_epochs=100

saver=tf.train.Saver()

# Launch the graph

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(n_epochs):
        total_batch=math.ceil(mnist.train.num_examples/batch_size)
        for epoch in range(total_batch):
            batch_features,batch_labels=mnist.train.next_batch(batch_size)
            sess.run(optimizer,feed_dict={features:batch_features,labels:batch_labels})
        # Print status for every 10 epochs
        if epoch % 10==0:
            valid_accuracy=sess.run(accuracy,feed_dict={features:mnist.validation.images,labels:mnist.validation.labels})
            print('Epoch {:<3} - Validation Accuracy :{} '.format(epoch,valid_accuracy))
    # Save the model
    saver.save(sess,save_file)
    print('Trained Model Saved')

Trained Model Saved


In [12]:
# Load a trained model

saver=tf.train.Saver()

# Launch the graph
with tf.Session() as sess:
    saver.restore(sess,save_file)
    test_accuracy=sess.run(accuracy,feed_dict={features:mnist.test.images,labels:mnist.test.labels})
    
print('Test Accuracy:{}'.format(test_accuracy))


INFO:tensorflow:Restoring parameters from ./train_model.ckpt
Test Accuracy:0.7275000214576721
