In [20]:
import tensorflow as tf

In [21]:
save_file='./model.ckpt'

In [22]:
# Two tensor variables:weights and bias
weights=tf.Variable(tf.truncated_normal([2,3]))
bias=tf.Variable(tf.truncated_normal([3]))

In [23]:
# Class used to save or restor Tensor Variables
saver=tf.train.Saver()

In [24]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))
    # Save the model
    saver.save(sess,save_file)

Weights:
[[ 0.50853342 -0.11600203  1.20777977]
 [-0.41503608  1.854895    0.74402231]]
Bias:
[ 0.94111675  0.78776634 -0.48341829]


In [25]:
# Remove the previous weights and bias
tf.reset_default_graph()

In [26]:
# Create 2 variables:weights,biases
weights=tf.Variable(tf.truncated_normal([2,3]))
bias=tf.Variable(tf.truncated_normal([3]))

saver=tf.train.Saver()

with tf.Session() as sess:
    saver.restore(sess,save_file)
    
    # Show the values of weights and biases
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))


INFO:tensorflow:Restoring parameters from ./model.ckpt
Weights:
[[-0.72124934 -1.4228735  -0.31917921]
 [ 0.30324054  0.36297545  0.93018091]]
Bias:
[-0.75918359 -0.32567054 -1.9453876 ]


In [27]:
# Let's see how to train a model and save its weights
# Remove previous Tensors and operations

tf.reset_default_graph()
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np


In [28]:
learning_rate=0.001
n_input=784
n_classes=10
mnist=input_data.read_data_sets('.',one_hot=True)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting ./train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting ./train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting ./t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting ./t10k-labels-idx1-ubyte.gz


In [29]:
# Features and labels
features=tf.placeholder(tf.float32,[None,n_input])
labels=tf.placeholder(tf.float32,[None,n_classes])

# Weights & bias

weights=tf.Variable(tf.random_normal([n_input,n_classes]))
bias=tf.Variable(tf.random_normal([n_classes]))

# logits -xW+b
logits=tf.add(tf.matmul(features,weights),bias)

# Define loss and optimizer

cost=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits,labels=labels))
optimizer=tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction=tf.equal(tf.argmax(logits,1),tf.argmax(labels,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction,tf.float32))




In [30]:
# Train the model
import math
save_file='./train_model.ckpt'
batch_size=128
n_epochs=100

saver=tf.train.Saver()

# Launch the graph

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(n_epochs):
        total_batch=math.ceil(mnist.train.num_examples/batch_size)
        for i in range(total_batch):
            batch_features,batch_labels=mnist.train.next_batch(batch_size)
            sess.run(optimizer,feed_dict={features:batch_features,labels:batch_labels})
        # Print status for every 10 epochs
        if epoch % 10==0:
            valid_accuracy=sess.run(accuracy,feed_dict={features:mnist.validation.images,labels:mnist.validation.labels})
            print('Epoch {:<3} - Validation Accuracy :{} '.format(epoch,valid_accuracy))
    # Save the model
    saver.save(sess,save_file)
    print('Trained Model Saved')

Epoch 0   - Validation Accuracy :0.10080000013113022 
Epoch 10  - Validation Accuracy :0.23399999737739563 
Epoch 20  - Validation Accuracy :0.3619999885559082 
Epoch 30  - Validation Accuracy :0.4602000117301941 
Epoch 40  - Validation Accuracy :0.5307999849319458 
Epoch 50  - Validation Accuracy :0.5878000259399414 
Epoch 60  - Validation Accuracy :0.6251999735832214 
Epoch 70  - Validation Accuracy :0.6538000106811523 
Epoch 80  - Validation Accuracy :0.6769999861717224 
Epoch 90  - Validation Accuracy :0.6976000070571899 
Trained Model Saved


In [31]:
# Load a trained model

saver=tf.train.Saver()

# Launch the graph
with tf.Session() as sess:
    saver.restore(sess,save_file)
    test_accuracy=sess.run(accuracy,feed_dict={features:mnist.test.images,labels:mnist.test.labels})
    
print('Test Accuracy:{}'.format(test_accuracy))


INFO:tensorflow:Restoring parameters from ./train_model.ckpt
Test Accuracy:0.7117999792098999
