In [198]:
import tensorflow as tf
import numpy as np

In [199]:
# 'tf.nn.con2d' requires the input be 4D(batch_size,height,width,depth)

x=np.array([[0,1,0.5,10],[2,2.5,1,-8],[4,0,5,6],[15,1,2,3]],dtype=np.float32)

In [200]:
x

array([[  0. ,   1. ,   0.5,  10. ],
       [  2. ,   2.5,   1. ,  -8. ],
       [  4. ,   0. ,   5. ,   6. ],
       [ 15. ,   1. ,   2. ,   3. ]], dtype=float32)

In [201]:
x=x.reshape((1,4,4,1))

In [202]:
x

array([[[[  0. ],
         [  1. ],
         [  0.5],
         [ 10. ]],

        [[  2. ],
         [  2.5],
         [  1. ],
         [ -8. ]],

        [[  4. ],
         [  0. ],
         [  5. ],
         [  6. ]],

        [[ 15. ],
         [  1. ],
         [  2. ],
         [  3. ]]]], dtype=float32)

In [203]:
X=tf.constant(x)
X

<tf.Tensor 'Const_22:0' shape=(1, 4, 4, 1) dtype=float32>

In [204]:
def conv2d(inputs):
    # The shape of the filter weight is(filter_height,filter_width,input_depth,output_depth)
    # The shape of the filter bias is output_depth
    # The output shape is (1,2,2,4)
    F_w=tf.Variable(tf.random_normal([2,2,1,3]))
    F_b=tf.Variable(tf.random_normal([3]))
    
    # Stride for each dimension: batch_size,filter_height,filter_width,depth
    strides = [1, 2, 2, 1]
    
    padding='SAME'
    
    return tf.nn.conv2d(inputs,F_w,strides,padding)+F_b

    

In [205]:
out=conv2d(X)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(out))

[[[[  3.6057539    4.0754838    9.4108572 ]
   [-14.4010601   -2.85576963   6.02873802]]

  [[ -5.58408213   8.70306396  25.53438377]
   [ -9.86263466   7.20039797  15.48938274]]]]


SAME Padding, the output height and width are computed as:

out_height = ceil(float(in_height) / float(strides[1]))

out_width = ceil(float(in_width) / float(strides[2]))

VALID Padding, the output height and width are computed as:

out_height = ceil(float(in_height - filter_height + 1) / float(strides[1]))

out_width = ceil(float(in_width - filter_width + 1) / float(strides[2]))