In [182]:
import tensorflow as tf
import numpy as np

In [183]:
# 'tf.nn.con2d' requires the input be 4D(batch_size,height,width,depth)

x=np.array([[0,1,0.5,10],[2,2.5,1,-8],[4,0,5,6],[15,1,2,3]],dtype=np.float32)

In [184]:
x

array([[  0. ,   1. ,   0.5,  10. ],
       [  2. ,   2.5,   1. ,  -8. ],
       [  4. ,   0. ,   5. ,   6. ],
       [ 15. ,   1. ,   2. ,   3. ]], dtype=float32)

In [185]:
x=x.reshape((1,4,4,1))

In [186]:
x

array([[[[  0. ],
         [  1. ],
         [  0.5],
         [ 10. ]],

        [[  2. ],
         [  2.5],
         [  1. ],
         [ -8. ]],

        [[  4. ],
         [  0. ],
         [  5. ],
         [  6. ]],

        [[ 15. ],
         [  1. ],
         [  2. ],
         [  3. ]]]], dtype=float32)

In [187]:
X=tf.constant(x)
X

<tf.Tensor 'Const_20:0' shape=(1, 4, 4, 1) dtype=float32>

In [188]:
def conv2d(inputs):
    # The shape of the filter weight is(height,width,input_depth,output_depth)
    # The shape of the filter bias is output_depth
    # The output shape is (1,2,2,4)
    F_w=tf.Variable(tf.random_normal([4,4,1,3]))
    F_b=tf.Variable(tf.random_normal([3]))
    
    # Stride for each dimension: batch_size,height,width,depth
    strides = [1, 2, 2, 1]
    
    padding='SAME'
    
    return tf.nn.conv2d(inputs,F_w,strides,padding)+F_b

    

In [189]:
out=conv2d(X)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(out))

[[[[ -5.10253048  -5.32559681  -2.20730758]
   [-18.18896866 -14.09578037  -3.03163052]]

  [[-20.20850945  -9.47641754 -11.95817375]
   [ -5.09834099   7.13857174  -5.99718904]]]]
