##### Set the values to 'strides' and 'ksize' such that the output shape after pooling is (1,2,2,1)


In [25]:
import tensorflow as tf
import numpy as np

In [26]:
x=np.array([[0,1,0.5,10],[2,2.5,1,-8],[4,0,5,6],[15,1,2,3]],dtype=np.float32)

In [27]:
x

array([[  0. ,   1. ,   0.5,  10. ],
       [  2. ,   2.5,   1. ,  -8. ],
       [  4. ,   0. ,   5. ,   6. ],
       [ 15. ,   1. ,   2. ,   3. ]], dtype=float32)

In [28]:
x=x.reshape((1,4,4,1))

In [29]:
x

array([[[[  0. ],
         [  1. ],
         [  0.5],
         [ 10. ]],

        [[  2. ],
         [  2.5],
         [  1. ],
         [ -8. ]],

        [[  4. ],
         [  0. ],
         [  5. ],
         [  6. ]],

        [[ 15. ],
         [  1. ],
         [  2. ],
         [  3. ]]]], dtype=float32)

In [30]:
X=tf.constant(x)

In [31]:
def maxpool(inputs):
    # Set the filter size for each dimension: batch_size,filter_height,filter_width,output_depth
    ksize=[1,2,2,1]
    # Set the stride for each dimension: 1,filter_height,filter_width,1
    strides=[1,2,2,1]
    padding='VALID'
    
    return tf.nn.max_pool(inputs,ksize,strides,padding)

out=maxpool(X)
    

In [32]:
with tf.Session() as sess:
    print(sess.run(out))
    

[[[[  2.5]
   [ 10. ]]

  [[ 15. ]
   [  6. ]]]]
